### PR TITLE
Linus/fix html redirection bug

### LINKED ISSUE #71: User can go to other websites using help command
user can access github using the help command and access other websites using the webview.
image

Possible fixes:
1. show local html file instead of website
2. use EventListener to prevent user from visiting other websites (maybe redirect if accessing different website)

### PR DESCRIPTION
**Pull request by zupey**
Closes #71 
# Description

Add warning to inform user that they are visiting a website outside of CLIMods.
image
Then, it reloads the page that they currently are at.

I know we discussed to just render the static HTML, but I came across this solution.  Can discuss if it's viable.

### CODE REVIEW

File: src/main/java/nus/climods/ui/common/HelpWindow.java [hunk 1]
```diff
@@ -102,24 +102,59 @@ public void setWindowDefaultSize(GuiSettings guiSettings) {
...
+                } else {
+                    webEngine.load(oldLocation);
+                }
+            }
+        });
+    }
+
+    private void showWarningMessage(String message) {
+        Alert alert = new Alert(Alert.AlertType.WARNING);
+        alert.setTitle("Warning");
```
Comment (SeekSaveServe) [inline src/main/java/nus/climods/ui/common/HelpWindow.java:153]: added this to wrap the warning message

**Review by SeekSaveServe — APPROVED** [review]
LGTM! I've commited some UI changes:
1. Make the mainwindow maximised by default to prevent certain parts from being cropped out due to the pref_height

2. Make the warning text wrap around in the dialog box in the help window so the full message gets displayed

**Review by sarrrdin — APPROVED** [review]
Works well on my device, LGTM 👍

File: src/main/java/nus/climods/ui/common/HelpWindow.java [hunk 2]
```diff
@@ -102,24 +102,61 @@ public void setWindowDefaultSize(GuiSettings guiSettings) {
...
+            Stream<String> lines = Files.lines(
+                Paths.get(ClassLoader.getSystemResource("html/UserManual.html").toURI())
+            );
+            webEngine.loadContent(lines.collect(Collectors.joining("\n")));
+        } catch (URISyntaxException | IOException e) {
+            logger.warning("User Manual not found!");
+        }
+    }
 
+    private boolean hasInternet() {
```
Comment (shenyih0ng) [inline src/main/java/nus/climods/ui/common/HelpWindow.java:126]: Just a consideration, do we want to put this as helper instead? I forsee we will be using this for our modules too

**Review by shenyih0ng — APPROVED** [review]
Thanks for working on this! This is great :D

File: src/main/java/nus/climods/ui/common/HelpWindow.java (hunk 1 above)
Comment (zupey) [reply src/main/java/nus/climods/ui/common/HelpWindow.java:153]: Thanks @SeekSaveServe

File: src/main/java/nus/climods/ui/common/HelpWindow.java (hunk 2 above)
Comment (zupey) [reply src/main/java/nus/climods/ui/common/HelpWindow.java:126]: Good idea!  I meant for this method to check for the availability of our github website only, since github can be down while the rest of the internet is up.  Perhaps I should name it better...

**Comment by zupey** [comment]
I renamed the method `hasInternet` to `isClimodsWebsiteUp` so the method's purpose is clearer.  If there's nothing else, let's merge this! Thanks everyone
